{
 "title": "Aldebaranode | Story Validator Dashboard",
 "description": "Dashboard metrics for story iliad network ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Blockheight",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "My Voting Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers Connected Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "Total Connected Peers" }
   ]
  },
  {
   "title": "Total Validators",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cometbft_consensus_validators", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Missing Validators",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"(en|eth|nic).*\", instance=\"193.34.212.192:9100\"}[$__rate_interval]) * 8",
     "legendFormat": "Receive Tx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"(en|eth|nic).*\", instance=\"193.34.212.192:9100\"}[$__rate_interval]) * 8",
     "legendFormat": "Transmit Tx"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"193.34.212.192:9100\", device=\"nvme0n1\"}[$__rate_interval])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"193.34.212.192:9100\", device=\"nvme0n1\"}[$__rate_interval])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}